"""add_transaction_to_group_column

Revision ID: 3bed4ac67844
Revises: b4ebbfe2b430
Create Date: 2025-12-12 14:17:38.513005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bed4ac67844"
down_revision = "b4ebbfe2b430"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("transaction_to_group", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "transaction_to_group")
    # ### end Alembic commands ###
