"""описание

Revision ID: 4703a23f226b
Revises: 3bed4ac67844
Create Date: 2025-12-13 12:31:38.436806

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "4703a23f226b"
down_revision = "3bed4ac67844"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("groups_name_key", "groups", type_="unique")
    op.drop_constraint("groups_owner_id_key", "groups", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("groups_owner_id_key", "groups", ["owner_id"])
    op.create_unique_constraint("groups_name_key", "groups", ["name"])
    # ### end Alembic commands ###
