"""описание

Revision ID: 4703a23f226b
Revises: 3bed4ac67844
Create Date: 2025-12-13 12:31:38.436806

"""
from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "4703a23f226b"
down_revision = "3bed4ac67844"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем ограничения только если они существуют
    # Используем DO блок для безопасного удаления
    op.execute(
        text(
            """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'groups_name_key'
                AND conrelid = 'groups'::regclass
            ) THEN
                ALTER TABLE groups DROP CONSTRAINT groups_name_key;
            END IF;

            IF EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'groups_owner_id_key'
                AND conrelid = 'groups'::regclass
            ) THEN
                ALTER TABLE groups DROP CONSTRAINT groups_owner_id_key;
            END IF;
        END $$;
    """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("groups_owner_id_key", "groups", ["owner_id"])
    op.create_unique_constraint("groups_name_key", "groups", ["name"])
    # ### end Alembic commands ###
