"""add_unique_constraint_user_id_in_group_members

Revision ID: 98927c5112d8
Revises: 4703a23f226b
Create Date: 2025-12-13 12:39:40.474186

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "98927c5112d8"
down_revision = "4703a23f226b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем уникальное ограничение на user_id, чтобы один пользователь мог состоять только в одной группе
    op.create_unique_constraint("uq_group_members_user_id", "group_members", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_group_members_user_id", "group_members", type_="unique")
    # ### end Alembic commands ###
