"""add user_id to transactions

Revision ID: b4ebbfe2b430
Revises: 5e86f51bebf6
Create Date: 2025-12-01 16:19:54.139301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4ebbfe2b430"
down_revision = "5e86f51bebf6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "transactions",
        "title",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "category",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "fk_transactions_user_id", "transactions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    
    # Условное удаление ограничений - используем SQL IF EXISTS
    # Проверяем и удаляем ограничения только если они существуют
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'users_email_key' 
                AND conrelid = 'users'::regclass
            ) THEN
                ALTER TABLE users DROP CONSTRAINT users_email_key;
            END IF;
            
            IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'users_username_key' 
                AND conrelid = 'users'::regclass
            ) THEN
                ALTER TABLE users DROP CONSTRAINT users_username_key;
            END IF;
        END $$;
    """)
    
    # Условное удаление индексов
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'ix_users_email' 
                AND tablename = 'users'
            ) THEN
                DROP INDEX IF EXISTS ix_users_email;
            END IF;
            
            IF EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'ix_users_username' 
                AND tablename = 'users'
            ) THEN
                DROP INDEX IF EXISTS ix_users_username;
            END IF;
        END $$;
    """)
    
    # Условное создание индексов - создаем только если они не существуют
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'ix_users_email' 
                AND tablename = 'users'
            ) THEN
                CREATE UNIQUE INDEX ix_users_email ON users (email);
            END IF;
            
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'ix_users_username' 
                AND tablename = 'users'
            ) THEN
                CREATE UNIQUE INDEX ix_users_username ON users (username);
            END IF;
            
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = 'ix_users_id' 
                AND tablename = 'users'
            ) THEN
                CREATE INDEX ix_users_id ON users (id);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_constraint("fk_transactions_user_id", "transactions", type_="foreignkey")
    op.alter_column(
        "transactions",
        "category",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "transactions",
        "title",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    op.drop_column("transactions", "user_id")
    # ### end Alembic commands ###
